### ISSUE TITLE
Propositions of new functions/functionalities

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#1]

**Comment by ItAlja** [comment]
Hi All !

Have youe ever heard about doSNOW package ?

Why do I mention it ?... This packages is using for multi-core training i.e. this is helpful as we're going to be train a lot of trees (cross validation). Inside doSNOW package we have nice function calling `makeCluster` - using this function I can say to my system: please work parallely.

Maybe this packages could be useful for us as well ?

What do you think ?

BR,
Ola

**Comment by MarcinKosinski** [comment]
There's also even `parallel` package in the `base R` with `mclapply` function that has the same syntax as regular `lapply`. 

Source: http://adv-r.had.co.nz/Functions.html

**Comment by Quares** [comment]
For parallelization i recommend "foreach" package developed by
Revolutionary R.

For training lots of trees, it would be helpful employ "ranger" package -
developed with the runtime optimization in mind.

Cheers,
K

**Comment by MarcinKosinski** [comment]
True. Boruta uses ranger:
https://cran.r-project.org/web/packages/ranger/index.html

2016-02-22 15:11 GMT+01:00 Kamil notifications@github.com:

**Comment by MarcinKosinski** [comment]
There were no proposiions for 5 months now. I am closing this as we will upload a package on CRAN soon with the simplest step search aglorihms basen on information_gain
