### ISSUE TITLE
Rewrite cut.off

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#12]
Go go super hero :) @DSkrzypiec

**Comment by DSkrzypiec** [comment]
Function FSelectorRcpp::cutOff_k() merges two functions from FSelector package: cutOff.k and cutOff.k.percent. If k in (0, 1] then cutOff_k() functions works like cutOff.k.percent function from R and when k > 1 then cutOff_k() works as cutOff.k for \floor(k) argument.

**Comment by MarcinKosinski** [comment]
@DSkrzypiec nice, so this is how those 2 functions can be merged in one function :) ? by this `k` parameter

**Comment by DSkrzypiec** [comment]
@MarcinKosinski yep, it already has been done :)

**Comment by MarcinKosinski** [comment]
Have we agreed that `cutoff.biggest.diff(attrs)` would be included in `cutOff_k()` when k is 0? @DSkrzypiec are you planning to include this feature? Can we then close this issue after a sweet commit :)?

**Comment by zzawadz** [comment]
I changed this function cutOff_k to cutOff_attrs -> it is something very similar but works for both character vector and data.frame returned by information_gain. I think it's a bit better approach:)

And one question left - with k == 1 -> we should return all attrs, or only first?

**Comment by MarcinKosinski** [comment]
I think we should only have data.frame approach as this is default behaviour in feature selection processes. 

For k == 1 it'l be good to return only 1 character. Returning all characters is done in information_gain :P

**Comment by MarcinKosinski** [comment]
Do you think only data.frame support is consistent approach :)?

**Comment by zzawadz** [comment]
@MarcinKosinski 
Better?:)

**Comment by MarcinKosinski** [comment]
Thanks, good job :)
