### ISSUE TITLE
Sparse matrix support

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#16]
I have added simple sparse matrix support for information_gain. It assumes that we have sparse matrix with factors (or integers), and dependent variable is also factor (or integer).

For now this hack is just a simple just a simple hack - I convert sparse matrix **column by column** (I don't convert whole matrix - just one column at a time!) to dense format and then apply our standard functions. This approach is not very memory (and probably performance) efficient, but it's simple, and it's works:D

But for the future We should prepare much more robust and elegant way of handling sparse matrices:)

**Comment by MarcinKosinski** [comment]
Great news! Good job

**Comment by MarcinKosinski** [comment]
Is it implemented in `sp_information_gain` https://github.com/mi2-warsaw/FSelectorRcpp/blob/master/R/information_gain.R#L70 ? Can we have one outer function `information_gain` (which would be overloaded for different input classes) that would check the type of `x` matrix and react under the hood variously for data frames and sparse matrixes? What do you think about such simplicity of user interface?

**Comment by MarcinKosinski** [comment]
Like in `?glmnet::glmnet`

>   x - input matrix, of dimension nobs x nvars; each row is an observation vector. Can be in sparse matrix format (inherit from class "sparseMatrix" as in package Matrix; not yet available for family="cox")

interface :

``` R
glmnet(x, y, family=c("gaussian","binomial","poisson","multinomial","cox","mgaussian"),
    weights, offset=NULL, alpha = 1, nlambda = 100,
    lambda.min........
```

**Comment by zzawadz** [comment]
Oki. I think it's good idea. However in this case we should resign from _(formula = y ~ x1 + x2 + ..., data = data)_ interface - don't think that sticking with two different ways of calling a function is the best idea:)

**Comment by MarcinKosinski** [comment]
Exactly :) I think `glmnet` formula isn't that bad :< and they have
experience with sparsity (sparse matrixes) :)

2016-05-19 9:37 GMT+02:00 Zygmunt Zawadzki notifications@github.com:

**Comment by zzawadz** [comment]
Oki. I will try to change this interface during my trip do Warsaw:)

**Comment by zzawadz** [comment]
I forgot to attach commit to this issue, but it's ready:)

Link to mentioned commit: 8ff3e8200e3c4f698b4bf9ed3a69b8c58b38c809
