### ISSUE TITLE
Authorship?

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#19]
@MarcinKosinski 
I need to copy one whole function from FSelector (we can't have FSelector in import field, because FSelector depends on Java, and we don't want to have any Java dependency problem).

How we should endorse original function author in our package?

**Comment by MarcinKosinski** [comment]
You can write in documentation file, that this function is copied from `FSelector`package and we can provide a link to CRAN?

**Comment by MarcinKosinski** [comment]
Moreover R is open-source and you can feel free to copy and re-use code :P
