### ISSUE TITLE
Who rewrites which functions?

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#2]
``` R
> library(FSelector)
> ls("package:FSelector", all.names = TRUE)
 [1] "as.simple.formula"        "backward.search"          "best.first.search"        "cfs"                     
 [5] "chi.squared"              "consistency"              "cutoff.biggest.diff"      "cutoff.k"                
 [9] "cutoff.k.percent"         "exhaustive.search"        "forward.search"           "gain.ratio"              
[13] "hill.climbing.search"     "information.gain"         "linear.correlation"       "oneR"                    
[17] "random.forest.importance" "rank.correlation"         "relief"                   "symmetrical.uncertainty"
```

**Comment by MarcinKosinski** [comment]
@ItAlja maybe you could have a look at `cfs filter` (correlation feature selection) algorithm ?

> The algorithm finds attribute subset using correlation and entropy measures for continous and discrete data.

which

> makes use of `best.first.search` for searching the attribute subset space.

or you could have a look at `best.first.search` itself?

``` R
 data(iris)

  subset <- cfs(Species~., iris)
  f <- as.simple.formula(subset, "Species")
  print(f)
```

The main goal for now is to have a look at the base code and decide whether this can be reimplemented, what are the cons of those implementation (so that we can extend our motivation in vignette) and basically what is done under the hood? Few sentences of the cfs algorithm summary could be very helpful :)

**Comment by MarcinKosinski** [comment]
@Quares do you think those functionalities:

``` R
cutoff.k(attrs, k)
cutoff.k.percent(attrs, k)
cutoff.biggest.diff(attrs)
```

could be merged in one function (even under better name)?

More over could you provide summary of what those functions do? What are they purpose and of course CONS, and maybe do you have any ideas on how C++ implementation could make benefit for those functions. Do this little subset of functions can be somehow extended?

**Comment by ItAlja** [comment]
@MarcinKosinski OK. I'll take a look at both.

**Comment by MarcinKosinski** [comment]
I'll have a look at `OneR` algorithm that uses association rules involving only one attribute in condition part + `consistency` - Consistency-based filter that inds attribute subset using consistency measure for continous and discrete data.

**Comment by MarcinKosinski** [comment]
@DSkrzypiec you can feel free to pick any function as you wish :)

**Comment by MarcinKosinski** [comment]
This can be closed so far as we are not planning rewriting more functions right now. We have few seraches, information gain (gain and symmetrical uncertainty) and cutoffs :) If one would like ever to rewrite more function than this can be opened
