### ISSUE TITLE
No to std::cout

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#20]
@DSkrzypiec 
If we plan CRAN release we can't use iostream and std::cout in our code:( It's causes this warning in R check:

```
File ‘FSelectorRcpp/libs/FSelectorRcpp.so’:
  Found ‘__assert_fail’, possibly from ‘assert’ (C)
    Object: ‘information_gain.o’
Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor the system RNG.
```

I've added special macro to handle this, you need to `#include "../FSelectorConfig.h"`, and then use `FS_OUTPUT` like this

```
FS_OUTPUT << " " << std::endl;
```

For now I think it's good solution to satify CRAN:) But feel free to use `std::cout` during development:D

**Comment by MarcinKosinski** [comment]
@DSkrzypiec you can close thise issue after you read Zygmunt's message
