### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#22]
@MarcinKosinski what do you think about going to CRAN with first release? I think it's quite stable and information_gain works pretty well, so maybe it's time?

**Comment by MarcinKosinski** [comment]
Let me have a greater look  at this package right now. I start right now.

**Comment by MarcinKosinski** [comment]
blocked by #7 #23 #25

**Comment by rajanandthakur** [comment]
@MarcinKosinski Thanks for creating this package. Do you have any plan to include more feature selection method ... may be within k fold cross-validation to avoid selecting features which might overfit ?

**Comment by MarcinKosinski** [comment]
This package was designed and created by @zzawadz : )

I think you can include your own feature evaluator in the
`exhaustive_search` and `greedy_search` function. The k fold
cross-validation is even included in examples, like here:
https://github.com/mi2-warsaw/FSelectorRcpp/blob/master/R/param_search.R#L34

2016-11-04 6:42 GMT+01:00 Thakur Raj Anand notifications@github.com:

**Comment by MarcinKosinski** [comment]
@krzyslom @zzawadz after saturday's dev-hackathon I think we'll be ready for CRAN.
I even think we are now ready for CRAN but additional check from Ola and Ala with a fresh eye would be ok : )

**Comment by zzawadz** [comment]
@MarcinKosinski @krzyslom we are very close. I fixed all warning in cpp code, and some other small issues, and it should be fine.

**Comment by MarcinKosinski** [comment]
Good job! Thanks 

Marcin Kosinski

Dnia 04.03.2017 o godz. 00:46 Zygmunt Zawadzki <notifications@github.com> napisał(a):

**Comment by MarcinKosinski** [comment]
Ok the submision process is finished.
We just need to resubmit new version with proper vignettes - #50
