### ISSUE TITLE
Vignette: Benchmark

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#25]

**Comment by zzawadz** [comment]
There should be no non-standard directories in main directory of our pkg. See the note from R CMD check

``` r
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘benchmarks’
```

I moved file from benchmarks to inst/benchmark. In general `inst` directory is a good place for all various things:)

**Comment by MarcinKosinski** [comment]
So probably it should be a good idea to add `benchmarks` to `.Rbuildignore`.
I think that benchmarks would take too long, so they shouldn't been run during CRAN CHECK or during package BUILD. I'll add raw code of benchmarks to one of vignettes but I'll give a link in that vignette to results of those benchmarks that I will upload to FSelectorRcpp's website

**Comment by zzawadz** [comment]
I think that everything placed in `inst` directory is not evaluated during build or check. Only thing from `tests` are used.

**Comment by MarcinKosinski** [comment]
Good :) I'll move benchmarks to vignettes anyway :P

2016-07-11 11:26 GMT+02:00 Zygmunt Zawadzki notifications@github.com:

**Comment by MarcinKosinski** [comment]
@krzyslom could you please provide a benchmark for `discretize`?

log(time) vs observations' volume WRAPED for number of columns

**Comment by MarcinKosinski** [comment]
http://mi2-warsaw.github.io/FSelectorRcpp/articles/benchmarks_discretize.html
