### ISSUE TITLE
discretization specified by a user

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#26]
How discretization is being done right now? https://github.com/mi2-warsaw/FSelectorRcpp/blob/master/src/discretize.cpp Do we cut continuous variable for 5 intervals where breaks are quantiles 20%, 40%, 60%, 80%?

Could this be specified by a user? On how many intervals this should be done? This could be an additional parameter in information_gain: intervals = 5 ?
The R logic for this parameter would be `cut(variable, breaks = quantile(variable, seq(0,1,length.out=intervals))` ?

**Comment by MarcinKosinski** [comment]
@zzawadz

**Comment by zzawadz** [comment]
No - we use Fayyad & Irani's MDL method (this is our port from RWeka, see this - http://www.inside-r.org/packages/cran/RWeka/docs/Normalize).

We can add your method, if you want:)

**Comment by MarcinKosinski** [comment]
Ok sory for being ignorant. So it's OK for me :) You can close this issue,
or we might think about letting user to choose discretization function and
set Fayyad & Irani's MDL as default function ?

2016-07-06 9:39 GMT+02:00 Zygmunt Zawadzki notifications@github.com:

**Comment by zzawadz** [comment]
We can add this in the next version;)

**Comment by MarcinKosinski** [comment]
good idea. so for now let's close this and let's reopoen this if there will
be future versions

2016-07-06 10:25 GMT+02:00 Zygmunt Zawadzki notifications@github.com:

**Comment by MarcinKosinski** [comment]
@zzawadz talking about discretization

I check our `discretization` function and for `iris` dataset so far it works the same as `RWeka::Discretization`

``` r
> library(RWeka)
> library(FSelectorRcpp)
> RWeka::Discretize(Species~Sepal.Length, data = iris)[, 1] -> Rweka_disc_out
> FSelectorRcpp::discretize(iris$Sepal.Length, iris$Species) ->FSelectorRcpp_disc_out
> table(Rweka_disc_out,FSelectorRcpp_disc_out)
               FSelectorRcpp_disc_out
Rweka_disc_out  (-Inf;5.550000] (5.550000;6.150000] (6.150000;Inf)
  '(-inf-5.55]'              59                   0              0
  '(5.55-6.15]'               0                  36              0
  '(6.15-inf)'                0                   0             55
```

but the interface is different than in `RWeka::Discretization` which is more `formula`-ish

do you think this is possible to use formula in our `discretize` function?

PS this function is faster than RWeka : )

``` r
> library(microbenchmark)
> microbenchmark(discretize(iris$Sepal.Length, iris$Species),
+                Discretize(Species~Sepal.Length, data = iris))
Unit: microseconds
                                            expr      min      lq      mean
     discretize(iris$Sepal.Length, iris$Species)  239.972  250.70  272.9375
 Discretize(Species ~ Sepal.Length, data = iris) 4884.355 5065.94 5359.3083
   median       uq      max neval
  272.572  290.325  322.731   100
 5226.550 5448.746 7444.139   100
```

**Comment by MarcinKosinski** [comment]
Ok sory, I see in the examples that this is possible :P

Shame on me....

**Comment by MarcinKosinski** [comment]
@zzawadz  Ok I'm back : P

We have incosistence in the output of FSelectorRcpp::discretize:

``` R
> head(discretize(Species ~ ., iris))
     Sepal.Length         Sepal.Width    Petal.Length     Petal.Width Species
1 (-Inf;5.550000]      (3.350000;Inf) (-Inf;2.450000] (-Inf;0.800000]  setosa
2 (-Inf;5.550000] (2.950000;3.350000] (-Inf;2.450000] (-Inf;0.800000]  setosa
3 (-Inf;5.550000] (2.950000;3.350000] (-Inf;2.450000] (-Inf;0.800000]  setosa
4 (-Inf;5.550000] (2.950000;3.350000] (-Inf;2.450000] (-Inf;0.800000]  setosa
5 (-Inf;5.550000]      (3.350000;Inf) (-Inf;2.450000] (-Inf;0.800000]  setosa
6 (-Inf;5.550000]      (3.350000;Inf) (-Inf;2.450000] (-Inf;0.800000]  setosa
> head(discretize(Species ~ Sepal.Length, iris))
     Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 (-Inf;5.550000]         3.5          1.4         0.2  setosa
2 (-Inf;5.550000]         3.0          1.4         0.2  setosa
3 (-Inf;5.550000]         3.2          1.3         0.2  setosa
4 (-Inf;5.550000]         3.1          1.5         0.2  setosa
5 (-Inf;5.550000]         3.6          1.4         0.2  setosa
6 (-Inf;5.550000]         3.9          1.7         0.4  setosa
> head(discretize(iris$Sepal.Length, iris$Species))
[1] (-Inf;5.550000] (-Inf;5.550000] (-Inf;5.550000] (-Inf;5.550000] (-Inf;5.550000] (-Inf;5.550000]
Levels: (-Inf;5.550000] < (5.550000;6.150000] < (6.150000;Inf)
> head(RWeka::Discretize(Species~Sepal.Length, data = iris))
   Sepal.Length Species
1 '(-inf-5.55]'  setosa
2 '(-inf-5.55]'  setosa
3 '(-inf-5.55]'  setosa
4 '(-inf-5.55]'  setosa
5 '(-inf-5.55]'  setosa
6 '(-inf-5.55]'  setosa
```

Depending whether we spciefy arguments as formula, or as separete `x` and `y` we have a `data.frame` or a `factor` vector. In my opinion it should be unioned, and the closest solution is to be backward comptabile in logic with the baseline (FSelector).
- Could we always have a data.frame as a result?
- If not full set of variables is used in formula, can the output data.frame can consist only in used features (param `all.features = FALSE`)?
- Can we specify additional parameter `all.features`(or whathever the name you think is proper) that will add additional features, not used in formula, but included in the used `data` parameter to the output data.frame (like this is done now)?

Should we split this to 3 separate taska?

**Comment by zzawadz** [comment]
You're right.

**Comment by MarcinKosinski** [comment]
@krzyslom please have a look if `discretize` output is consistent : )
If not please reorganize.

**Comment by krzyslom** [comment]
@MarcinKosinski Briefly about overall style: changed equality signs to arrows, made brackets consistent and kept 80 characters max per line.

As for the output, there are 2 new convenience methods in utils file for handling input. I figured out that the simplest way to obtain consistent output is to mutate input of different classes and pass it to the formula method. Now one can pass a numeric vector, list, matrix or data.frame to x and y.

**Comment by MarcinKosinski** [comment]
Thanks @krzyslom for creating a unified output for various input types.
This function can be marked as checked and ready to go.
