### ISSUE TITLE
Sponsorship : ideas

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#3]
- WCO [assignee : @MarcinKosinski]
- European Union

Any more ideas? Once can edit my question.

**Comment by MarcinKosinski** [comment]
A może google scholar?
@zzawadz  @ItAlja @Quares 

http://www.r-bloggers.com/r-projects-at-google-summer-of-code-2016/

**Comment by ItAlja** [comment]
Good idea !

**Comment by MarcinKosinski** [comment]
So we should submit this project with description but we need to have 2 tutors (I have no idea whether they'll get paid) and submit person who'll receive payment (but they need to be students:P). 

I can submit some overview of the project. Is there anyone, besides me, who's still a student?

**Comment by Quares** [comment]
Guys,

It basically works the other way around.

People who submit proposals are called "mentors". Only mentors from the
pre-chosen organizations can upload proposals. The org application ended on
19th Feb. Furthemore, the soft-deadline for proposals submissions was on
the 1st of March.

Now, with proposals already approved, everyone can sign-up to take part in
this project. Once chosen, such a person becomes a "student" and will earn
$$ for his/her work. Note that you don't actually have to be an university
student.

The schema described above allows organizations to post their projects and
pay prospective people $$ for developing code for them. Therefore, unless
you are willing to pay $$ to someone, I don't know how FSelectorRcpp could
benefit from that.

-K

**Comment by zzawadz** [comment]
And we are not students:)

**Comment by Quares** [comment]
Like I mentioned. I don't think that you need to be an academic student
(most likely it is actually even better if you aren't). It's just a figure
of speech.

**Comment by ItAlja** [comment]
Sometimes 'student' means any of person who would like take a part in the particular project. Anyway, not this time. Detailed info is here:
https://developers.google.com/open-source/gsoc/faq

**Comment by Quares** [comment]
It seems I was wrong, you actually have to be a 'student':

What are the eligibility requirements for participation?
- You must be at least 18 years of age
- You must be a full or part-time student at an accredited
  https://developers.google.com/open-source/gsoc/faq#accredited university
  (or have been accepted as of April 22, 2016)
- You must be eligible to work in the country you will reside in during
  the program
- You have not already participated as a Student in GSoC more than twice
- You must reside in a country that is not currently embargoed by the
  United States. See Program Rules for more information.

**Comment by MarcinKosinski** [comment]
@zzawadz @DSkrzypiec we promote `FSelectorRcpp` package as

>  Rcpp (free of Java/Weka) implementation of FSelector entropy-based feature selection algorithms with sparse matrix support

so basically if `information_gain` is finished and we'll have final version of `cuttOff_k` (that will also provide an interface to FSelector::cutoff.big.diff https://github.com/mi2-warsaw/FSelectorRcpp/issues/12) then a simple feature selection workflow is available. I  would call this ver 0.1.0.

To provide more complicated algorithms it'll be great to provide Rcpp implementations of 
- best.first.search
- backward.search 
- exhaustive.search
- forward.search

functions in on function called something like `stepwise_search` with parameter `method  = c("best.fisrt", "backward", "exhaustive", "forward")` [https://github.com/mi2-warsaw/FSelectorRcpp/issues/13] and then I'll call that ver 0.2.0 and we could submit FSelectorRcpp to CRAN with 3 basic functions: 
- `information_gain`
- `cufOff_k`
- `stepwise_search`

and motivation vignette [https://github.com/mi2-warsaw/FSelectorRcpp/issues/7]

Then we could encourage students from Faculty of Mathematics and Information Science (Warsaw University of Technology), writing master thesis in the bio-stat-inf MiNI+MIMUW group https://github.com/geneticsMiNIng/geneticsMiNIng.github.io , to extend implementations in FSelectorRcpp as a part of their master thesis. 

What do you think of that?

**Comment by MarcinKosinski** [comment]
It looks like we probably won't have huge aspirations for sponsorship. If anyone have any ideas in the future, feel free to open this issue. It'll be easier If one of us were a scientist with science grand
