### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#35]
@zzawadz have you seen http://r-addict.com/#comment-2879769941  ?

**Comment by zzawadz** [comment]
@MarcinKosinski - strange - works for me...

I'll think about it...

**Comment by MarcinKosinski** [comment]
There is a problem on appveyor: https://ci.appveyor.com/project/MarcinKosinski/fselectorrcpp

**Comment by MarcinKosinski** [comment]
We can see `red X` marks near commits history that state the build is unstable :P 
https://github.com/mi2-warsaw/FSelectorRcpp/commits/master

**Comment by zzawadz** [comment]
Yeah, but it's a problem with RJava. I need to dive into appveyor, and find out why RJava cannot be loaded.

**Comment by zzawadz** [comment]
I am waiting for a result:)

**Comment by zzawadz** [comment]
@MarcinKosinski - appveyor fixed:D Another green badge! It's better than pokemon!
