### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by drowca** [mi2-warsaw/FSelectorRcpp#36]
I got this error when trying to install the package. I run R version 3.2.5, Platform: x86_64-pc-linux-gnu (64-bit)

The error message pasted below:

g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -fopenmp -I../inst/include  -I"/home/owca/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/owca/R/x86_64-pc-linux-gnu-library/3.2/BH/include" -I"/home/owca/R/x86_64-pc-linux-gnu-library/3.2/RcppArmadillo/include" -I"/home/owca/R/x86_64-pc-linux-gnu-library/3.2/testthat/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c support.cpp -o support.o
support.cpp: In function ‘Rcpp::IntegerVector fs_table1d(SEXPREC*&)’:
support.cpp:140:10: error: ‘strncmp’ is not a member of ‘std’
       if(std::strncmp(xx.attr("class"), "factor", 6) == 0)
          ^
support.cpp:140:10: note: suggested alternative:
In file included from /usr/share/R/include/R_ext/RS.h:26:0,
                 from /usr/share/R/include/R.h:50,
                 from /home/owca/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/r/headers.h:52,
                 from /home/owca/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/RcppCommon.h:29,
                 from /home/owca/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp.h:27,
                 from support.cpp:1:
/usr/include/string.h:147:12: note:   ‘strncmp’
 extern int strncmp (const char *__s1, const char *__s2, size_t __n)
            ^
make: *** [support.o] Błąd 1
ERROR: compilation failed for package ‘FSelectorRcpp’
* removing ‘/home/owca/R/x86_64-pc-linux-gnu-library/3.2/FSelectorRcpp’
BŁĄD: Command failed (1)

**Comment by MarcinKosinski** [comment]
@drowca do you Have RTools?
Can you also upload result of 'devtools::session_info()?'

**Comment by drowca** [comment]
Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.5 (2016-04-14)
 system   x86_64, linux-gnu           
 ui       RStudio (0.98.490)          
 language (EN)                        
 collate  pl_PL.UTF-8                 
 tz       <NA>                        
 date     2017-02-13

**Comment by MarcinKosinski** [comment]
@drowca do you have RTools https://cran.r-project.org/bin/windows/Rtools/ ?

What about upgrading R to 3.3.2 - https://www.r-statistics.com/2013/03/updating-r-from-r-on-windows-using-the-installr-package/?

**Comment by drowca** [comment]
I don't have RTools. I'm confused, the link you provided is for R on Windows and I run Linux, so do I need them? 
Anyway, I'll upgrade R and I'll try to install FSelectorRcpp again, let's see if it helps.

**Comment by drowca** [comment]
Done. R upgrade to ver 3.3.2 helped, the package was successfully installed. Thanks for the support.

**Comment by krzyslom** [comment]
Thanks for reporting the issue. I've added R version dependency to the package. As for the RTools - it's Windows feature only. I tried to install FSelectorRcpp on Windows 7 and the pop-up came out with information that RTools has to be installed first. After this step there was no problem with installing FSelectorRcpp.

**Comment by MarcinKosinski** [comment]
Good job  @krzyslom
