### ISSUE TITLE
Add package skeleton

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#4]
Like here http://r-pkgs.had.co.nz/package.html

@Quares you could try to do this, since whis will be new for you

**Comment by zzawadz** [comment]
I added simple skeleton, but someone is needed to fill Description file;)

**Comment by MarcinKosinski** [comment]
We'll finished `DESCRIPTION` at the end. As it is done with `introduction` to master thesis :)

**Comment by Quares** [comment]
Sorry, I joined the Repo only yesterday and did not receive a notification that I was assigned to this one.

**Comment by MarcinKosinski** [comment]
No problemo compadre

2016-02-08 11:43 GMT+01:00 Kamil notifications@github.com:
