### ISSUE TITLE
Discretize - arguments

### ISSUE THREAD

**Issue by AleksandraDabrowska** [mi2-warsaw/FSelectorRcpp#46]
`discretize(x = iris[[1]], y = iris[[5]],k=2)`  - unused argument k , but there is no warning

`discretize(x = iris[[1]], y = iris[[5]], control = list(equalsizeControl(k = -1)), keepAll = TRUE, call = NULL)`  -for k smaller than zero or non-integer we should get error (R encountered a fatal error)

**Comment by MarcinKosinski** [comment]
I have added special `stopifnot` condition to the `equalsizeControl` about `k`. I have renamed `keepAll` to `all` and extended it's documentation to be more clear.  Thanks for suggestions.

I can not fix anyway the issue with no warning when you pass unneeded parameters  as this is the deep Rcpp dependency issue :)
