### ISSUE TITLE
Error when column names are not syntactically valid variable names

### ISSUE THREAD

**Issue by khotilov** [mi2-warsaw/FSelectorRcpp#52]
E.g., this results in error:
```
> df <- data.frame(a=0:1, "b + c"=3:4, check.names=F)
> FSelectorRcpp::information_gain(a ~ ., df)
Error in `[.data.frame`(data, c(formula$x, formula$y)) : 
  undefined columns selected
```
The problem comes from `attr(terms(a ~ ., data=df), "term.labels")` returning such column names enclosed in `` ` ` ``

**Comment by MarcinKosinski** [comment]
@zzawadz @krzyslom : O

**Comment by MarcinKosinski** [comment]
@khotilov I think the easiest way is not to use such `fancy` names : )
