### ISSUE TITLE
100% coverage

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#55]

**Comment by MarcinKosinski** [comment]
A perfect candidate for a Won't fix :)

**Comment by zzawadz** [comment]
Not really. I believe that shouldn't be such a big deal.

**Comment by MarcinKosinski** [comment]
When an issue becames outdated? Do we have any X days limit?

**Comment by zzawadz** [comment]
> When an issue becames outdated? Do we have any X days limit?

@MarcinKosinski today. We have 97%.

**Comment by MarcinKosinski** [comment]
Wow

pon., 5 lis 2018, 12:27: Zygmunt Zawadzki <notifications@github.com>
napisał(a):
