### ISSUE TITLE
R^2 example in feature search.

### ISSUE THREAD

**Issue by krzyslom** [mi2-warsaw/FSelectorRcpp#59]
In documentation of feature_search the second example utilises R^2 statistic. It is trivial because the result will always be the best for the biggest model. I've tried the same thing with Adjusted R^2 and the result happens to be the same. Maybe we could think about a better example that will show the essence of feature selection?

**Comment by MarcinKosinski** [comment]
It is not TRUE that the bigger model gets bigger R^2. Just try to add random variables to the model And R^2 will decrease with the number of random variables
