### ISSUE TITLE
Sparse data set

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#6]

**Comment by zzawadz** [comment]
@MarcinKosinski can you provide example of sparse data set? We need one for examples and for developing.

**Comment by MarcinKosinski** [comment]
Sure. Give me a second.

**Comment by MarcinKosinski** [comment]
# Creating from scratch

``` R
> library(Matrix)
> help(package="Matrix")
> ## simple example
> i <- c(1,3:8); j <- c(2,9,6:10); x <- 7 * (1:7)
> (A <- sparseMatrix(i, j, x = x))
8 x 10 sparse Matrix of class "dgCMatrix"

[1,] . 7 . . .  .  .  .  .  .
[2,] . . . . .  .  .  .  .  .
[3,] . . . . .  .  .  . 14  .
[4,] . . . . . 21  .  .  .  .
[5,] . . . . .  . 28  .  .  .
[6,] . . . . .  .  . 35  .  .
[7,] . . . . .  .  .  . 42  .
[8,] . . . . .  .  .  .  . 49
> summary(A)
8 x 10 sparse Matrix of class "dgCMatrix", with 7 entries 
  i  j  x
1 1  2  7
2 4  6 21
3 5  7 28
4 6  8 35
5 3  9 14
6 7  9 42
7 8 10 49
> str(A) # note that *internally* 0-based row indices are used
Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:7] 0 3 4 5 2 6 7
  ..@ p       : int [1:11] 0 0 1 1 1 1 2 3 4 6 ...
  ..@ Dim     : int [1:2] 8 10
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : NULL
  ..@ x       : num [1:7] 7 21 28 35 14 42 49
  ..@ factors : list()
```

# Converting from regular objects

http://stackoverflow.com/a/10555270/3857701

# Usage of sparse matrix in `glmnet`
- http://web.stanford.edu/~hastie/glmnet/glmnet_alpha.html#spa
- http://www.r-bloggers.com/genetic-data-large-matrices-and-glmnet/

# Further reading

http://www.johnmyleswhite.com/notebook/2011/10/31/using-sparse-matrices-in-r/

**Comment by zzawadz** [comment]
Oki. So our interface should be similar to glmnet?

**Comment by MarcinKosinski** [comment]
I think regular `formula` interface is more robust and popular. If this is
possible for sparse support then I'll suggest sticking to `formula`
inferace. `glmnet` has parameter inferface

2016-02-08 12:18 GMT+01:00 Zygmunt Zawadzki notifications@github.com:

**Comment by zzawadz** [comment]
Oki. Fine. Thanks:)

I have one more question - what is stored in columns? Values that we should treat as a factor, numeric variables (and we need to discretize them) or counts (sth similar to result of a table function?)

**Comment by MarcinKosinski** [comment]
If a matrix contains only numeric variables than it is hard to store them in sparse format (but it should be discretized to make entropy calculations easier). If a Column contains a discrete variable with many levels than it can be changed to dummy variables with sparse.matrix.model function. I think we can provide a mechanism that would change inputed that into sparse.model.matrix if special parameter would be passed. If not we assume that sparse matrix is passed or regular data frame. 

Marcin Kosinski

Dnia 08.02.2016 o godz. 19:16 Zygmunt Zawadzki notifications@github.com napisał(a):
