### ISSUE TITLE
Discretize warning

### ISSUE THREAD

**Issue by krzyslom** [mi2-warsaw/FSelectorRcpp#60]
Discretize shows warning for skipped non numeric columns even for ```all = TRUE```.

**Comment by SteveBronder** [comment]
Didn't want to open a new issue, but compilation also shows a warning for a missing switch statement when compiling discretize

```clang
In file included from discretize.cpp:1:
In file included from ./discretizeControlR.h:5:
../inst/include/discretize/discretize.h:24:10: warning: enumeration value 'UNKNOWN' not handled in switch [-Wswitch]
  switch(method)
         ^
../inst/include/discretize/discretize.h:24:10: note: add missing switch cases
  switch(method)
         ^
```

Didn't know if fall through was intended here so did not want to make a new issue
