### ISSUE TITLE
Get back to CRAN

### ISSUE THREAD

**Issue by MarcinKosinski** [mi2-warsaw/FSelectorRcpp#69]

**Comment by twolodzko** [comment]
Please consider editing the NEWS file to provide information for the users why did the package disappear from CRAN and what was fixed.

**Comment by MarcinKosinski** [comment]
Is there a way I can help here somehow?

**Comment by zzawadz** [comment]
@MarcinKosinski I'll write an excuse why we were out of the CRAN (it was just a silly problem with building process), and resubmit the pkg.

**Comment by MarcinKosinski** [comment]
We are back again!
