### ISSUE TITLE
Create functions for entropy based filters

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#8]
We have all building blocks to create following functions on R side:

``` r
information.gain(formula, data) #(it's nearly ready)
gain.ratio(formula, data)
symmetrical.uncertainty(formula, data)
```

For now - they should work only with data.frames without NA's (I'am working on this on the c++ side).

Any volunteer?

**Comment by ItAlja** [comment]
If only I can help somehow -> I'll do !
First of all I'll send to you some conclusion about `cfs filter` and `best.first.search` as I promised.

sorry for delay, I was sick and then I had to catch up with my work.

**Comment by MarcinKosinski** [comment]
Those are almost the same functions. Maybe we should only have `information_gain` as the implementation of `FSelector:::information.gain.body`

**Comment by zzawadz** [comment]
Oki. I merged them into one - information_gain with parameter `type = c("infogain", "gainratio", "symuncert")`

**Comment by MarcinKosinski** [comment]
@zzawadz  could you add number of issue to commits ? 
like `git commit -m "merge for #8"` - then your change will appear in the issue tree and it will be easier to check what's going on :)

**Comment by zzawadz** [comment]
Oki. I forgot:(

**Comment by MarcinKosinski** [comment]
@zzawadz I've check parameter names in `Information_gain`
It is a little bit confusing right now :P

Can we have 
1. `x = attributes, y = response`
2. `formula = response name ~ names in dataset, data = dataset`
parameters specification?

So when one specifies `x` and `y` then `data` and `formula` are not used, and symetrically one can specify `formula` and `data` without specifing `x` and `y`. In case someone specifies confusingly `x`, `y` and for example `data` then we should stop with the error message.

Is that doable? It would make interface easie for regular data analyst

**Comment by zzawadz** [comment]
But it will spoil my beautiful S3 classes:)

But ok - I seems more consistent.

**Comment by zzawadz** [comment]
I've implemented that, but I'm not really happy from it:(

In old version I was able to use it like that:

``` r
information_gain(Species ~ ., iris)
```

now I have to add this formula and data keywords:

``` r
information_gain(formula = Species ~ ., data = iris)
```

**Comment by MarcinKosinski** [comment]
Hmm

information_gain(Species ~ ., iris) - this looks great
information_gain(Species ~ ., y = iris) - looked confusing last time :/

so maybe let's do it like this - (reorder parameters)

information_gain <- function(formula, data, x, y)

so that

information_gain(Species ~ ., iris) this is default run where iris is data :) ?

2016-07-06 10:24 GMT+02:00 Zygmunt Zawadzki notifications@github.com:

**Comment by MarcinKosinski** [comment]
Thanks @zzawadz for this one :)
