### ISSUE TITLE
Installation bug: "Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character(): argument is of length zero"

### ISSUE THREAD

**Issue by hermidalc** [mi2-warsaw/FSelectorRcpp#80]
R 3.5.1 on Fedora 30 Linux

Error when trying to install:
```
> install.packages("FSelectorRcpp")
trying URL 'https://cloud.r-project.org/src/contrib/FSelectorRcpp_0.3.1.tar.gz'
Content type 'application/x-gzip' length 71817 bytes (70 KB)
==================================================
downloaded 70 KB

* installing *source* package ‘FSelectorRcpp’ ...
** package ‘FSelectorRcpp’ successfully unpacked and MD5 sums checked
** libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
```

**Comment by hermidalc** [comment]
Sorry appears to be an issue with my R install

**Comment by schienstockd** [comment]
@hermidalc I ran into this issue in a couple of Biocondutor packages - can you share what your solution was?

**Comment by hermidalc** [comment]
@schienstockd use the conda prebuilt package https://anaconda.org/r/r-fselectorrcpp

**Comment by hermidalc** [comment]
Also, if you aren't using Anaconda but instead Mambaforge/Miniforge (which I am) where this prebuilt package isn't available, I just tested the manual build on my Linux box, I created a conda-forge env with the only the latest `r-base` and then with it activated within R `install.packages("FSelectorRcpp")` and everything builds no problem.

**Comment by schienstockd** [comment]
Great, Thanks! I had to clean up my conda environment a bit with `conda clean -a`. There were some packages that R got confused with.
