### ISSUE TITLE
RWeka::Discretize works and produces correct results while FSelectorRcpp::discretize issues many "Cannot find any split points for `Col_XXX`. Drops this column." warnings and incorrect results

### ISSUE THREAD

**Issue by hermidalc** [mi2-warsaw/FSelectorRcpp#81]
I'm trying to use FSelectorRcpp::discretize as a drop-in replacement for RWeka::Discretize because it is so much faster and doesn't have to deal with the RJava mess.  RWeka::Discretize always works with any dataset and produces downstream results that are in line with expectations (where e.g I know the ground truth or when compared to other methods that do not use discretization).

But FSelectorRcpp::discretize with the exact same datasets can issue many ``"Cannot find any split points for `Col_XXX`. Drops this column."`` warnings and produces downstream results that are definitely not correct.

What could be the differences?

**Comment by MarcinKosinski** [comment]
Hey @hermidalc can you provide a [reprex](https://www.tidyverse.org/help/)! and provide your `devtools::session_info()`?
