### ISSUE TITLE
Handling NA's

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#9]
I think we should add support for NA (and I am working on this).

It should be just 10% time overhead - so I don't think that is a big deal:)

**Comment by zzawadz** [comment]
I added support for NA in fs_discretize - but only for independent variable.

NA for dependent variable is far more tricky, so I need to think a little:)

**Comment by MarcinKosinski** [comment]
In which file I can check this support on in which commit? did you know you can add `mention #9` messages to commit so that your commits will appear in the issue tree?

**Comment by MarcinKosinski** [comment]
example: git add commit -m "added support for NAs #9"

**Comment by MarcinKosinski** [comment]
@zzawadz I've seen that in `FSelector` they were ommiting rows with NAs in dependent variable. Maybe we should do this the same way?

**Comment by MarcinKosinski** [comment]
I am strongly convinced that handling NAs should be just a simple row removal for those observations that have NA in any feature or explanatory variable. @zzawadz then can we close this issue?

**Comment by zzawadz** [comment]
I'm not sure, but for now it might be a good idea to use this approach:)

I'll update the code in the evening.

**Comment by MarcinKosinski** [comment]
remember to `message #9` in the commit :)

2016-05-16 8:52 GMT+02:00 Zygmunt Zawadzki notifications@github.com:

**Comment by khotilov** [comment]
Handling of missing values would be a very useful feature for selectors that have simple algorithmic options for that. Please do not dismiss this issue.

E.g., here are two possible options for information gain:
- assume that missingness is completely at random, and redistribute the counts of missing values across other values in proportion to their frequency (default setting of Weka's `InfoGainAttributeEval`)
- assume that missing values are very special and treat them as a separate value for entropy calculations (that's what `FSelector::information.gain` does, and that's what `InfoGainAttributeEval` would do when a `-M` option is passed to it)

**Comment by MarcinKosinski** [comment]
@zzawadz if the second options is compatible with the FSelector, we might consider this : )
